### ISSUE TITLE
First execution / NoClassDefFoundError

### ISSUE THREAD

**Issue by lipki** [CallMeFoxie/MewnbaseModded#5]
`java -jar build/libs/MewnBaseModded-1.0-SNAPSHOT.jar `

> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	( ... )
> Caused by: java.lang.ClassNotFoundException: com.badlogic.gdx.ApplicationListener
> 	( ... )

In the "jar" the class does not exist, I add it by hand.
but ..

> Exception in thread "main" java.lang.NoClassDefFoundError: com/codedisaster/steamworks/SteamFriendsCallback
> 	at com.cairn4.moonbase.desktop.DesktopLauncher.main(DesktopLauncher.java:22)
> Caused by: java.lang.ClassNotFoundException: com.codedisaster.steamworks.SteamFriendsCallback
>  	( ... )

I add it by hand.
but ..

> MewnBase launch args: 
> java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFWErrorCallbackI
> 	at com.cairn4.moonbase.desktop.DesktopLauncher.main(DesktopLauncher.java:42)
> Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFWErrorCallbackI
>  	( ... )

I add (org) it by hand.
but ..

> MewnBase launch args: 
> com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'libgdx64.so' for target: Linux, 64-bit
> 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:125)
>  	( ... )
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Unable to read file for extraction: libgdx64.so
>  	( ... )

**Comment by lipki** [comment]
Well, I'm coming to nothing, I'll try to redo everything, on a new project.
I would have a better understanding of what I'm doing.

**Comment by CallMeFoxie** [comment]
The libgdx64.so should be packed when you run ./gradlew idea

Also how did you add that .jar manually?

**Comment by lipki** [comment]
"./gradlew idea" does not produce a jar
I'm doing ".gradlew build".

I think, I have problems of "dependency". Obviously.
And I'm going to understand well ... maybe.
libgdx64.so is not add, and there is other error after.
But ... I launch the game in IDEA.
So, there is progress.

**Comment by lipki** [comment]
I open jar like zip, and add file in.
